language: go

env:
  - GO111MODULE=on

go:
  - 1.13.x

os: 
  - linux

install: true

script:
  - go test -v -race ./...
  - env GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o ocfl-Linux-x86_64 ./cmd/ocfl
  - env GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o ocfl-Darwin-x86_64 ./cmd/ocfl
  - env GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o ocfl-Windows-x86_64.exe ./cmd/ocfl

deploy:
  provider: releases
  api_key: $DEPLOY_KEY
  file:
    - ocfl-Linux-x86_64
    - ocfl-Darwin-x86_64
    - ocfl-Windows-x86_64.exe
  skip_cleanup: true
  on:
    tags: true
